### PR TITLE
added traefik labels, reformatted rules templ to be easier to read

### PR DESCRIPTION
**Pull request by cpoole**

### CODE REVIEW

**Comment by cpoole** [comment]
in this commit I added a manual option for configuring the front end. I also added the option to set a backend proxy listener to https. 

finally I used the new whitespace trim feature from go 1.6 to make the rules.toml.tmpl easier to read

**Comment by cpoole** [comment]
you can take a look at my community catalog if you want to run this yourself to test https://github.com/cpoole/community-catalog. If you like any of these features I can update the readme in the community catalog and submit a pull request as well.

**Comment by rawmind0** [comment]
Hi @cpoole ,

i'm sorry about the delay....:P

First of all, thanks for the PR. 
- Manual option may be some problematic. Manual mode couldn't assure that the service fqdn's to publish in traefik are unique. That's why i take the way to add sevice_name and stack_name to the domain to form service fqdn, because it assure that the names are unique. 

This package is thought to run as a global stack, i mean 1 traefik stack is giving access to all the services that wants to publish itself. In that way, it's very important to control that service fqdn's are unique. If you duplicate one service fqdn, the same host rule would be added to two different frontend's, but traefik'd be working without any problem, no error, no log....Only the first host rule ocurrence could match, then the other never match, which would be the correct one?? I mean with it that it's not so trivial to detect and correct a duplicated service fqdn.

IMHO, the manual mode, would be a nice feature to run traefik in a "local" mode, but it's not in a global mode. It would be easy to create a new traefik package to run traefik in a local mode, may be by stack and add manual mode. What do you think??
- In the last commit in alpine-traefik, https://github.com/rawmind0/alpine-traefik/commit/04505da458b74ad1660a39beab749e463f5c6dad , i've added to the package a variable TRAEFIK_HTTPS_ENABLE to control entrypoints listener:
  - if TRAEFIK_HTTPS_ENABLE="false", then TRAEFIK_ENTRYPOINTS="http"
  - if TRAEFIK_HTTPS_ENABLE="only", then TRAEFIK_ENTRYPOINTS="https"
  - if TRAEFIK_HTTPS_ENABLE="true", then TRAEFIK_ENTRYPOINTS="http","https"
    With it, you could control how to publish your services. Services would be exposed in all the TRAEFIK_ENTRYPOINTS available. 
    Would it works for you instead of https label in the services?? 
- The new go 1.6 template notation, very cool!!! It really was a nightmare to write and read templates....Thanks a lot.. 👍 

best regards... :)

**Comment by cpoole** [comment]
Hey @rawmind0 no worries about the delay.

I totally understand the reasoning for building the fqdns with the stack and service names. The reason I added the manual option is because I needed to run two services in a single stack that had single subdomain fqdns (subdomain1.domain.com and subdomain2.domain.com).

```
Stack:
    Service: subdomain1.domain.com
    Service: subdomain2.domain.com
```

I recognize that's a pretty fringe use-case but it's one I stumbled across. How would you propose solving that?

As for the TRAEFIK_HTTPS_ENABLE that feature looks great 👍 thanks for adding that. 

The https feature I added was for the backend though. Say I have a service running in a container that _requires_ it run on https. I needed a way to prefix the backend url with https instead of http. You can take a look on lines 16-20 of the rules.toml.tmpl to see how I did that. I believe your most recent commits have not addressed this issue. 

Thanks again!

**Pull request closed without merging**
